/*
 * Created by Bob Shen on 18-8-9 下午5:28
 * Copyright(c) 2018. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ayst_stresstest_util_MemOpUtils */

#ifndef _Included_com_ayst_stresstest_util_MemOpUtils
#define _Included_com_ayst_stresstest_util_MemOpUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ayst_stresstest_util_MemOpUtils
 * Method:    memfill
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ayst_stresstest_util_MemOpUtils_malloc(JNIEnv *, jclass, jint size);

/*
 * Class:     com_ayst_stresstest_util_MemOpUtils
 * Method:    memfree
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_com_ayst_stresstest_util_MemOpUtils_free(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
